add_newline = true

[character]
format = '$symbol  '
success_symbol = '''\(Â´âˆ€`\)'''
error_symbol = '''\(ï¾‰âˆ€`\)'''

[line_break]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[time]
disabled = false
format = "ğŸ•™[$time]($style) "
time_format = "%R"

[battery]
full_symbol = "ï‰€ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ï‰ "

[[battery.display]]
threshold = 100
style = "bold green"

[hg_branch]
disabled = false

[sudo]
disabled = false

[aws]
symbol = "î­ " # U+E7AD, Devicons
[azure]
symbol = "ó¿´ƒ "
[dart]
symbol = "î˜ " # U+E798, Devicons
[docker_context]
symbol = "î° " # U+E7B0, Devicons
[dotnet]
symbol = "î¿ " # U+E77F, Devicons
[gcloud]
symbol = "î² " # U+E7B2, Devicons
[git_branch]
symbol = "îœ‚ " # U+E702, Devicons
[golang]
symbol = "îœ¤ " # U+E724, Devicons
[java]
symbol = "îœ¸ " # U+E738, Devicons
[julia]
symbol = "î˜¤ " # U+E624, Seti-UI + Custom
[lua]
symbol = "î˜  " # U+E620, Seti-UI + Custom
[nodejs]
symbol = "îœ˜ " # U+E718, Devicons
[perl]
symbol = "î© " # U+E769, Devicons
[php]
symbol = "îœ½ " # U+E73D, Devicons
[python]
symbol = "îœ¼ " # U+E73C, Devicons
[ruby]
symbol = "îœ¹ " # U+E739, Devicons
[rust]
symbol = "î¨ " # U+E7A8, Devicons
[scala]
symbol = "îœ· " # U+E737, Devicons
[swift]
symbol = "î• " # U+E755, Devicons
