add_newline = true

[character]
success_symbol = '''\(Â´âˆ€`\)'''
error_symbol = '''\(ï¾‰âˆ€`\)'''

[gcloud]
disabled = true

[line_break]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[time]
disabled = false
utc_time_offset = 9
format = "ğŸ•™[$time]($style) "
time_format = "%R"

[battery]
full_symbol = "ï‰€ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ï‰ "

[[battery.display]]
threshold = 100
style = "bold green"

[aws]
symbol = "î­ "
[docker]
symbol = "î° "
[dotnet]
symbol = "î¿ "
[git_branch]
symbol = "îœ‚ "
disabled = false
[golang]
symbol = "îœ¤ "
[haskell]
symbol = "î· "
[java]
symbol = "îœ¸ "
[nodejs]
symbol = "îœ˜ "
[php]
symbol = "îœ½ "
[python]
symbol = "îœ¼ "
[ruby]
symbol = "îœ¹ "
[rust]
symbol = "î¨ "
