add_newline = true

[character]
success_symbol = '''\(´∀`\)'''
error_symbol = '''\(ﾉ∀`\)'''

[gcloud]
disabled = true

[line_break]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[time]
disabled = false
utc_time_offset = 9
time_format = "%H:%M"

[battery]
full_symbol = " "
charging_symbol = "⚡️ "
discharging_symbol = " "

[[battery.display]]
threshold = 100
style = "bold green"

[aws]
symbol = " "
[docker]
symbol = " "
[dotnet]
symbol = " "
[git_branch]
symbol = " "
disabled = false
[golang]
symbol = " "
[haskell]
symbol = " "
[java]
symbol = " "
[nodejs]
symbol = " "
[php]
symbol = " "
[python]
symbol = " "
[ruby]
symbol = " "
[rust]
symbol = " "
