gui:
  nerdFontsVersion: "3"
  statusPanelView: allBranchesLog
  timeFormat: "2006-01-02T15:04:05Z07:00"
  shortTimeFormat: "15:04"
git:
  branchLogCmd: git log --graph --date=short --pretty=short-oneline --color=always
  allBranchesLogCmds:
    - git log --all --graph --date=short --pretty=short-oneline --color=always
  pagers:
    - externalDiffCommand: "difft --color=always --display=inline"
keybinding:
  universal:
    quit: <c-c>
    return: q
    gotoTop: g
    gotoBottom: G
  commits:
    renameCommit: "<disabled>"
    viewResetOptions: r
  stash:
    popStash: p
