## ddu
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hooks_file = '$STD_CONFIG/dpp/ddu.lua'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_cmd = 'Ddu'
group = 'ddu'

### UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
group = 'ddu'

### Matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
group = 'ddu'

[[plugins]]
repo = 'mityu/ddu-filter-matcher_multi_regex'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
group = 'ddu'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
group = 'ddu'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'
group = 'ddu'

### Sources
[[plugins]]
repo = 'Shougo/ddu-source-action'
group = 'ddu'

[[plugins]]
repo = 'matsui54/ddu-source-help'
group = 'ddu'

[[plugins]]
repo = 'matsui54/ddu-source-man'
group = 'ddu'

[[plugins]]
repo = '4513ECHO/ddu-source-source'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-source-file'
group = 'ddu'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
group = 'ddu'

[[plugins]]
repo = 'shun/ddu-source-buffer'
group = 'ddu'

[[plugins]]
repo = 'shun/ddu-source-rg'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-source-register'
group = 'ddu'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
group = 'ddu'

### Kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
group = 'ddu'

### column
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
group = 'ddu'
